import ViewToggle from "./ViewToggle.tsx";
import type {ViewMode} from "../types/ViewMode.ts";
import axios from "axios";
import {useEffect} from "react";

export default function Header({
    view,
    onChangeView
}: Readonly<{
    view: ViewMode;
    onChangeView: (view: ViewMode) => void;
}>) {

    // Redirect to the backend for authentication
    function login() {
        const backendUrl =
            window.location.host === "localhost:5173"
                ? "http://localhost:8080"
                : window.location.origin;

        window.open(backendUrl + "/oauth2/authorization/github", "_self");
        // The URL /oauth2/authorization/github is automatically generated by Spring Security,
        // and it redirects the user to the GitHub OAuth login
    }

    // Retrieving information about the authorized user
    const loadUser = () => {
        axios.get("/api/auth/me")
            .then(response => console.log(response.data));
    }

    // Check if a user is still logged-in after a page refresh
    useEffect(() => {
        loadUser();
    }, []);

    return (
        <header className="relative bg-slate-900 text-white py-5 px-6 shadow-lg">
            <div className="max-w-5xl mx-auto text-center">
                <h1 className="text-4xl md:text-5xl font-bold tracking-tight">
                    Restaurant Finder
                </h1>
                <ViewToggle view={view} onChangeView={onChangeView} />
            </div>

            <button
                className="absolute right-6 top-1/2 -translate-y-1/2 bg-white text-slate-900 px-4 py-2 rounded-md active:scale-95"
                onClick={login}
            >
                Login
            </button>
        </header>
    )
}