spring.application.name=backend

spring.security.oauth2.client.registration.github.client-id=${GITHUB_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_SECRET}
spring.security.oauth2.client.registration.github.scope=none

app.frontend-url=http://localhost:5173/

geoapify.app.key=${API_KEY}